Define Angular Services for Wallet Account Backup
prysmaticlabs/prysm-web-ui pull request #169
Opened 2021-03-15 21:31 UTC by olehyev138

Back up component created.

Accounts form selection component created for representing the selection of the accounts in the Backup and Exit of the accounts

added button on the actions for navigating to the backup page

2021-03-15 22:23 UTC, rauljordan commented
We definitely need to find a solution or an alternative approach, this UI does not look good at all. However, I understand this is more of a task for a designer. We will look into this a bit later.

<img width="1122" alt="Screen Shot 2021-03-15 at 5 20 41 PM" src="https://user-images.githubusercontent.com/5572669/111228828-dfc78580-85b2-11eb-9923-388e68aa3fcd.png">

There is no need for 3 buttons. We only need Cancel and Submit, with standard spacing between them
<img width="1122" alt="Screen Shot 2021-03-15 at 5 21 09 PM" src="https://user-images.githubusercontent.com/5572669/111228941-0e456080-85b3-11eb-9f2c-4e212ed6a77c.png">

2021-03-16 08:11 UTC, rkapka requested changes
I can click the button without selecting any accounts. It should not be possible to back up 0 accounts.

2021-03-16 08:11 UTC, rkapka commented on src/app/modules/wallet/pages/account-backup/account-backup.component.html
> +                Backup Selected Account(s)
```suggestion
                Back Up Selected Account(s)
```

2021-03-16 08:11 UTC, rkapka commented on src/app/modules/wallet/components/account-actions/account-actions.component.html
> +      Back up accounts
```suggestion
      Back Up Accounts
```
For consistency with other buttons.

2021-03-16 08:11 UTC, rkapka commented on src/app/modules/wallet/pages/account-backup/account-backup.component.ts
> +          'Error happened while backing up the accounts'
```suggestion
          'An error occurred during backup'
```

2021-03-16 12:06 UTC, olehyev138 commented on src/app/modules/wallet/pages/account-backup/account-backup.component.ts
> +          'Error happened while backing up the accounts'
all fixed

2021-03-17 10:37 UTC, rkapka approved these changes

2021-03-17 10:37 UTC, merged