Import/Export Slashing Protection
prysmaticlabs/prysm-web-ui pull request #170
Opened 2021-03-17 22:10 UTC by olehyev138

Created Two components slashing protection component. for managing import or export of the slashing components. Import Protection component responsible for importing the slashing protections.

Abstracted the import component dropzone.

Created an extension file and extended the Date object with an additional method.

2021-03-17 23:23 UTC, rauljordan commented on src/app/modules/wallet/components/import-protection/import-protection.component.html
> +        Import Slashing protections
```suggestion
        Import Slashing Protection
```

2021-03-17 23:23 UTC, rauljordan commented on src/app/modules/wallet/components/import-protection/import-protection.component.html
> +            Upload any folder of slashing protection files
```suggestion
            Upload your slashing protection file. To read more about how to obtain this file, see our documentation portal <a href="https://docs.prylabs.network/docs/wallet/slashing-protection">here</a>
```

2021-03-17 23:24 UTC, rauljordan commented
<img width="1205" alt="Screen Shot 2021-03-17 at 6 24 14 PM" src="https://user-images.githubusercontent.com/5572669/111551367-0837b700-874e-11eb-8862-62274e11e979.png">
The text is a little cut off here. The breadcrumb should also say "slashing" instead of "slashin"

2021-03-18 09:25 UTC, rkapka commented on src/app/modules/wallet/pages/slashing-protection/slashing-protection.component.html
> +            <div class="text-white text-3xl">Import/Export Slashing protection</div>
```suggestion
            <div class="text-white text-3xl">Import/Export Slashing Protection</div>
```

2021-03-18 09:25 UTC, rkapka commented on src/app/modules/wallet/pages/slashing-protection/slashing-protection.component.html
> +                        Import a slashing protection Json
```suggestion
                        Import a slashing protection JSON
```

2021-03-18 09:25 UTC, rkapka commented on src/app/modules/wallet/pages/slashing-protection/slashing-protection.component.html
> +                        Get a slashing protection Json
```suggestion
                        Get a slashing protection JSON
```

2021-03-18 09:25 UTC, rkapka commented on src/app/modules/wallet/pages/slashing-protection/slashing-protection.component.ts
> +          const fileName = `slashingp-protections${d.toDateTimeString()}.json`;
```suggestion
          const fileName = `slashing-protection-${d.toDateTimeString()}.json`;
```

2021-03-18 09:25 UTC, rkapka commented on src/app/modules/wallet/components/import-protection/import-protection.component.ts
> +              'Error happened while import your slashing protection'
```suggestion
              'An error occured while importing your slashing protection'
```

2021-03-18 09:31 UTC, rkapka requested changes
I think there are a few things missing.

1. There is no confirmation after a successful import.
2. https://deploy-preview-170--prysm-web-ui.netlify.app/dashboard/wallet/accounts/import displays a few nice things: number of files uploaded, error when the format is wrong (although the styling is a little bit off), etc. We should have the same in slashing protection import.
3. We can probably make a common component for both slashing protection upload and the upload from the previous point, which includes all the nice things mentioned in (2), so that we can reuse it everywhere. I guess the file format should be a parameter.

2021-03-19 08:07 UTC, rkapka commented on src/app/modules/shared/components/import-accounts-form/import-accounts-form.component.html
> +    <!-- <div class="my-6 flex flex-wrap">
Please remove commented code.

2021-03-19 08:07 UTC, rkapka commented on src/app/modules/shared/components/import-accounts-form/import-accounts-form.component.html
> +      <!-- <mat-error *ngIf="invalidFiles.length">
Please remove commented code.

2021-03-19 08:12 UTC, rkapka requested changes
Please remove dead code.

2021-03-19 13:36 UTC, rkapka approved these changes

2021-03-19 13:36 UTC, merged